os:
- linux

language: php

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

php:
  - 7.1
  - 7.2

notifications:
  email: false
