<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'kartenmacherei\\restframework\\abstractquerylocator' => '/Action/AbstractQueryLocator.php',
                'kartenmacherei\\restframework\\abstractresourcerequest' => '/ResourceRequest/AbstractResourceRequest.php',
                'kartenmacherei\\restframework\\abstractrouter' => '/Router/AbstractRouter.php',
                'kartenmacherei\\restframework\\action' => '/Action/Action.php',
                'kartenmacherei\\restframework\\command' => '/Action/Command.php',
                'kartenmacherei\\restframework\\commandlocator' => '/Action/CommandLocator.php',
                'kartenmacherei\\restframework\\commandlocatorchain' => '/Action/CommandLocatorChain.php',
                'kartenmacherei\\restframework\\content' => '/Response/Content/Content.php',
                'kartenmacherei\\restframework\\contentresponse' => '/Response/ContentResponse.php',
                'kartenmacherei\\restframework\\contenttype' => '/Response/Content/ContentType.php',
                'kartenmacherei\\restframework\\encodeexception' => '/Response/Content/EncodeException.php',
                'kartenmacherei\\restframework\\errorexception' => '/ErrorException.php',
                'kartenmacherei\\restframework\\errorhandler' => '/ErrorHandler.php',
                'kartenmacherei\\restframework\\factory' => '/Factory.php',
                'kartenmacherei\\restframework\\framework' => '/Framework.php',
                'kartenmacherei\\restframework\\getrequestmethod' => '/Request/GetRequestMethod.php',
                'kartenmacherei\\restframework\\httpheader' => '/Response/HttpHeader.php',
                'kartenmacherei\\restframework\\jsoncontent' => '/Response/Content/JsonContent.php',
                'kartenmacherei\\restframework\\jsoncontenttype' => '/Response/Content/JsonContentType.php',
                'kartenmacherei\\restframework\\methodnotallowedresponse' => '/Response/MethodNotAllowedResponse.php',
                'kartenmacherei\\restframework\\nomorelocatorsexception' => '/Action/NoMoreLocatorsException.php',
                'kartenmacherei\\restframework\\nomoreroutersexception' => '/Router/NoMoreRoutersException.php',
                'kartenmacherei\\restframework\\notfoundresponse' => '/Response/NotFoundResponse.php',
                'kartenmacherei\\restframework\\optionsrequestmethod' => '/Request/OptionsRequestMethod.php',
                'kartenmacherei\\restframework\\optionsresponse' => '/Response/OptionsResponse.php',
                'kartenmacherei\\restframework\\patchrequestmethod' => '/Request/PatchRequestMethod.php',
                'kartenmacherei\\restframework\\pattern' => '/Request/Pattern.php',
                'kartenmacherei\\restframework\\postrequestmethod' => '/Request/PostRequestMethod.php',
                'kartenmacherei\\restframework\\putrequestmethod' => '/Request/PutRequestMethod.php',
                'kartenmacherei\\restframework\\query' => '/Action/Query.php',
                'kartenmacherei\\restframework\\querylocator' => '/Action/QueryLocator.php',
                'kartenmacherei\\restframework\\querylocatorchain' => '/Action/QueryLocatorChain.php',
                'kartenmacherei\\restframework\\readandwriterestresource' => '/Resource/ReadAndWriteRestResource.php',
                'kartenmacherei\\restframework\\readonlyrestresource' => '/Resource/ReadOnlyRestResource.php',
                'kartenmacherei\\restframework\\request' => '/Request/Request.php',
                'kartenmacherei\\restframework\\requestmethod' => '/Request/RequestMethod.php',
                'kartenmacherei\\restframework\\resourcerequest' => '/ResourceRequest/ResourceRequest.php',
                'kartenmacherei\\restframework\\resourcerequesthandler' => '/ResourceRequest/ResourceRequestHandler.php',
                'kartenmacherei\\restframework\\response' => '/Response/Response.php',
                'kartenmacherei\\restframework\\restresource' => '/Resource/Resource.php',
                'kartenmacherei\\restframework\\restresourceexception' => '/Resource/RestResourceException.php',
                'kartenmacherei\\restframework\\router' => '/Router/Router.php',
                'kartenmacherei\\restframework\\routerchain' => '/Router/RouterChain.php',
                'kartenmacherei\\restframework\\unsupportedrequestmethodexception' => '/Request/UnsupportedRequestMethodException.php',
                'kartenmacherei\\restframework\\uri' => '/Request/Uri.php',
                'kartenmacherei\\restframework\\uriexception' => '/Request/UriException.php',
                'kartenmacherei\\restframework\\writeonlyrestresource' => '/Resource/WriteOnlyRestResource.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
