<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'kartenmacherei\\basketservice\\application' => '/Application.php',
                'kartenmacherei\\basketservice\\basketquerylocator' => '/RestResource/Basket/BasketQueryLocator.php',
                'kartenmacherei\\basketservice\\basketresourcerequest' => '/RestResource/Basket/BasketResourceRequest.php',
                'kartenmacherei\\basketservice\\basketrouter' => '/RestResource/Basket/BasketRouter.php',
                'kartenmacherei\\basketservice\\getbasketquery' => '/RestResource/Basket/GetBasketQuery.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
